Algoritmo "Exercicio 4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Laço de Repetição - Repita|Ate
// Autor(a)    : Maira Cardoso Carvalho
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
  n1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
n1<-15

Repita
  Escreval("O quadrado equivalente ao numero ",n1, " é", n1*n1)
  n1<- n1 + 1
Ate n1 >200
Fimalgoritmo